# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

test_suite(
    name = "integration",
    tests = [
        "//tests/integration/complex_monitoring",
        "//tests/integration/crash_ignores_dependents",
        "//tests/integration/crash_on_startup",
        "//tests/integration/fallback_to_same_target_restarts",
        "//tests/integration/incorrect_config_non_reporting",
        "//tests/integration/lm_shutdown_during_rt_switch",
        "//tests/integration/lm_shutdown_during_switch_to_off",
        "//tests/integration/parallel_launch",
        "//tests/integration/process_complex_rep_failure",
        "//tests/integration/process_crash_monitoring",
        "//tests/integration/process_fd_leak",
        "//tests/integration/process_launch_args",
        "//tests/integration/process_simple_rep_failure",
        "//tests/integration/process_wrong_binary_failure",
        "//tests/integration/ready_conditions/file_state/exists:ready_condition_file",
        "//tests/integration/ready_conditions/file_state/not_existing:ready_condition_file_not_exists",
        "//tests/integration/rt_running_when_process_exits",
        "//tests/integration/sandbox_options",
        "//tests/integration/shutdown_signal",
        "//tests/integration/smoke",
        "//tests/integration/switch_run_target",
    ],
)
